[project]
authors = ["Alex Kerney <abk@mac.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "climatology_py_dash"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]
edit = "marimo edit"
app = "marimo run climatology.py"
serve = "marimo run climatology.py --host 0.0.0.0 -p 8080 --base-url /climatology"

[dependencies]
erddapy = ">=2.2.4,<3"
xarray = ">=2025.4.0,<2026"
marimo = ">=0.13.6,<0.14"
altair = ">=5.5.0,<6"
pillow = ">=11.1.0,<12"
numpy = "<2.2.3"
libgfortran5 = "!=13.2.0"
python = ">=1.13"
vegafusion = ">=2.0.2,<3"
vegafusion-python-embed = ">=1.6.9,<2"
vl-convert-python = ">=1.7.0,<2"
pyarrow = ">=20.0.0,<21"
