name: "Push"

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-24.04
    timeout-minutes: 10

    steps:
    - name: "Checkout"
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.7.1
    
    - name: Cache Docker image
      uses: actions/cache@v4
      with:
        path: /tmp/image.tar
        key: neracoos-climatology-image-${{ github.sha }}
        restore-keys: |
          neracoos-climatology-image-
    
    - name: "Login to Docker Hub"
      uses: docker/login-action@v3.3.0
      continue-on-error: true
      with:
        username: gmri
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      uses: docker/build-push-action@v6.15.0
      with:
        context: .
        push: false
        tags: gmri/neracoos-climatology-py-dash:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
        outputs: type=docker,dest=/tmp/image.tar

  push:
    name: Push Docker Image and update GitOps config
    needs: build
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    
    if: |
      github.repository == 'gulfofmaine/climatology_py_dash'
      && github.ref == 'refs/heads/main'

    steps:
    - name: "Checkout"
      uses: actions/checkout@v4

    - name: Get tag name
      id: tagName
      run: echo "tag=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Cache Docker image
      uses: actions/cache@v4
      with:
        path: /tmp/image.tar
        key: neracoos-climatology-image-${{ github.sha }}

    - name: Load Docker image
      run: |
        docker load --input /tmp/image.tar
        docker image ls -a

    - name: "Login to Docker Hub"
      uses: docker/login-action@v3.3.0
      with:
        username: gmri
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Push Docker Image
      run: |
        docker tag gmri/neracoos-climatology-py-dash:latest gmri/neracoos-climatology-py-dash:${{ steps.tagName.outputs.tag }}
        docker push gmri/neracoos-climatology-py-dash:${{ steps.tagName.outputs.tag }}

    - name: Make GitOps directory
      run: mkdir gitops

    - name: Clone GitOps config repo
      working-directory: ./gitops
      env:
          GITOPS_TOKEN: ${{ secrets.GITOPS_TOKEN }}
      run: git clone "https://$GITOPS_TOKEN@github.com/gulfofmaine/neracoos-aws-cd.git"

    - name: Update GitOps config repo
      working-directory: ./gitops/neracoos-aws-cd
      run: |
          sed -i 's/?ref=.\+/?ref=${{ github.sha }}/' overlays/climatology_py_dash/kustomization.yaml
          sed -i 's/newTag: .\+/newTag: "${{ steps.tagName.outputs.tag }}"/' overlays/climatology_py_dash/kustomization.yaml
          git config --global user.email 'neracoos-mariners-ci@gmri.org'
          git config --global user.name 'NERACOOS climatology_py_dash Dashboard CI'
          git diff --exit-code && echo 'Already Deployed' || (git commit -am 'Upgrade climatology_py_dash Dashboard to ${{ steps.tagName.outputs.tag }}' && git push)
